### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by StarsTesla** [prs-eth/Dynamic-LiDAR-Resimulation#4]
![image](https://github.com/prs-eth/Dynamic-LiDAR-Resimulation/assets/45264423/d9bde1bf-8730-4444-9d80-3582cb915753)

**Comment by StarsTesla** [comment]
I remove those args on command line and modify these args in python file, it works, but CUDA OOM, I run on 3060 12GB

**Comment by StarsTesla** [comment]
I change to 4090, but it is very slowly, is this normal?
![image](https://github.com/prs-eth/Dynamic-LiDAR-Resimulation/assets/45264423/2a46cde5-4020-452f-94c4-6f26fc7574bb)
![image](https://github.com/prs-eth/Dynamic-LiDAR-Resimulation/assets/45264423/c2f455d5-8ff3-45cc-99a2-2441148b2302)

**Comment by StarsTesla** [comment]
new errors when try to visualize model:
![image](https://github.com/prs-eth/Dynamic-LiDAR-Resimulation/assets/45264423/520a9f8d-34e7-4193-9072-be05fce37d10)
![image](https://github.com/prs-eth/Dynamic-LiDAR-Resimulation/assets/45264423/7b7443d2-5425-40d6-82f7-6690d3be69d2)

**Comment by StarsTesla** [comment]
Ok，finally I vis it, and the result shows some noisey points, not like the results in readme
![image](https://github.com/prs-eth/Dynamic-LiDAR-Resimulation/assets/45264423/1df677bb-3274-44a8-b46d-676169d63e77)

**Comment by StarsTesla** [comment]
I change this vis code, the static pred mask seems not good?, include almost many vehicle points, so the ray hit points should be all ray hit drop or the static scene?
![image](https://github.com/prs-eth/Dynamic-LiDAR-Resimulation/assets/45264423/b18d511a-c7af-4b79-8d1e-ba743360415e)
![img_v3_02bd_d7b6c128-87f2-4d06-8f1e-2913cbdf857g](https://github.com/prs-eth/Dynamic-LiDAR-Resimulation/assets/45264423/becd2aa8-ce96-46d8-96d8-b237fd2b6550)

**Comment by hanfeng-wu** [comment]
> I change to 4090, but it is very slowly, is this normal? ![image](https://private-user-images.githubusercontent.com/45264423/335129992-2a46cde5-4020-452f-94c4-6f26fc7574bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MDAyNjIsIm5iZiI6MTcxNzY5OTk2MiwicGF0aCI6Ii80NTI2NDQyMy8zMzUxMjk5OTItMmE0NmNkZTUtNDAyMC00NTJmLTk0YzQtNmYyNmZjNzU3NGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE4NTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MzZmMmUxYzlhMWQ2NWE1Zjc0ZGZhMTcxNWJiMjAzNGI3NGE0MTQyODAxOGI3ODIzYmIxYjBhYjMzMDJiMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FIvYOtewuhvWBkhDEyG5AQV_zXVmvIjzAEp7f0mJgU8) ![image](https://private-user-images.githubusercontent.com/45264423/335130124-c2f455d5-8ff3-45cc-99a2-2441148b2302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MDAyNjIsIm5iZiI6MTcxNzY5OTk2MiwicGF0aCI6Ii80NTI2NDQyMy8zMzUxMzAxMjQtYzJmNDU1ZDUtOGZmMy00NWNjLTk5YTItMjQ0MTE0OGIyMzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE4NTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YzMyMDA0YjVlOWNlODFkYjRkMjZkYjUxMjM0NmY4MTU5YzU2ODRiZWU4MmRhNDI2MWZlMTZhMGFjNWFhMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OGm4_etnwwvVEkzREv7NY6ZCKWh5DmkHc1TutPYPjWI)

Yes, the runtime is normal

**Comment by hanfeng-wu** [comment]
> I change this vis code, the static pred mask seems not good?, include almost many vehicle points, so the ray hit points should be all ray hit drop or the static scene? ![image](https://private-user-images.githubusercontent.com/45264423/335432544-b18d511a-c7af-4b79-8d1e-ba743360415e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MDAyNjIsIm5iZiI6MTcxNzY5OTk2MiwicGF0aCI6Ii80NTI2NDQyMy8zMzU0MzI1NDQtYjE4ZDUxMWEtYzdhZi00Yjc5LThkMWUtYmE3NDMzNjA0MTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE4NTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZjMyYjE4NjhiNWZjZjhjMzE3YjFmZGFjMDA1NWMwYWMyNjRiYzEyNTU3NjUyMWNiODdlNWEyOTk1YzBiMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c_Dvp2RIwec8PVe0yjcJEY1Tw1SIXyNzieTHlOAHBb0) ![img_v3_02bd_d7b6c128-87f2-4d06-8f1e-2913cbdf857g](https://private-user-images.githubusercontent.com/45264423/335431965-becd2aa8-ce96-46d8-96d8-b237fd2b6550.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MDAyNjIsIm5iZiI6MTcxNzY5OTk2MiwicGF0aCI6Ii80NTI2NDQyMy8zMzU0MzE5NjUtYmVjZDJhYTgtY2U5Ni00NmQ4LTk2ZDgtYjIzN2ZkMmI2NTUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE4NTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYTc0MGZkMDVlMGJhZDAyZTcwNTgzMDBjNjAxYWMyZDA4YzY5ZDI2NzU1MDkzZWJiMDQ4NmY3Y2RjZDg4MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xejFVD00bo1MwBwkv-cOIT_o0UXo2ssmIk--vKbqwPA)

I think this modification is also valid, in [this code](https://github.com/prs-eth/Dynamic-LiDAR-Resimulation/blob/b6d03de50ea84b98f685899240e1d8704523f95a/DyNFL/NFLStudio/nflmodel.py#L207C17-L207C31) I aggregated the raydrop probability for both static and dynamic part together, so the final ray_hit_mask should be for the whole scene.

**Comment by hanfeng-wu** [comment]
> Ok，finally I vis it, and the result shows some noisey points, not like the results in readme ![image](https://private-user-images.githubusercontent.com/45264423/335428355-1df677bb-3274-44a8-b46d-676169d63e77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MDAyNjIsIm5iZiI6MTcxNzY5OTk2MiwicGF0aCI6Ii80NTI2NDQyMy8zMzU0MjgzNTUtMWRmNjc3YmItMzI3NC00NGE4LWI0NmQtNjc2MTY5ZDYzZTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE4NTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4N2FkOWY3MzY1MGNhMmM3YjhiNWZjZDBlOTFiODgxZGUxMDY1MmM4ODllNTM2NTUzOTNmOTZhZDEyZDFkZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UNf_OijzxF-uy13m8nzyuQUAR0snss-ZiERGV3WBdLU)

Indeed, there seems to be more noisy points then usual. If you stick to our training pipeline, I think there might be some problems in training process. Can you also share your training curves and maybe the quantitative results for this scene?

**Comment by booker-max** [comment]
> ![image](https://private-user-images.githubusercontent.com/45264423/335061338-d9bde1bf-8730-4444-9d80-3582cb915753.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjI3NTUsIm5iZiI6MTcyMTcyMjQ1NSwicGF0aCI6Ii80NTI2NDQyMy8zMzUwNjEzMzgtZDliZGUxYmYtODczMC00NDQ0LTlkODAtMzU4MmNiOTE1NzUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA4MTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZDFlMGMwNjIwYjk5MTg2YzM2NTg2MjE1MTgxMjFhZmFhNjhlYmU3ODk0ZTU2YTUyYzBlMmFjOWFiMTQyZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t4qz11304et8plZwkiHNXkTtKB94F2ySB3PEC7qmbXc)

Hello, I also encountered this problem. Do I have to remove those args on command line? Is there any other solution? I think it is a bit troublesome to change the data type in this way.
