### ISSUE TITLE
运行训练代码报错

### ISSUE THREAD

**Issue by booker-max** [prs-eth/Dynamic-LiDAR-Resimulation#7]
当我运行训练代码ns-train NFLStudio --pipeline.datamanager.dataparser-config.context_name 1005081002024129653_5313_150_5333_150 --pipeline.datamanager.dataparser-config.root_dir /mnt/csi-data-aly/user/jinwang03/code/Dynamic-LiDAR-Resimulation/processed_data_dynamic --experiment_name debug，报错
![image](https://github.com/user-attachments/assets/63d7b2ec-1722-4f8d-9ba5-8091883faa16)
请问我可以怎么解决呢，谢谢

**Comment by hanfeng-wu** [comment]
Hi, I think it's --pipeline.datamanager.dataparser-config.context-name rather than context_name, if it does not work, you can try to pre enter the context_name and root_dir in NFLStudio/dataparser.py and run ``ns-train NFLStudio`` without args
