### ISSUE TITLE
about metrics result

### ISSUE THREAD

**Issue by cqf7419** [prs-eth/Dynamic-LiDAR-Resimulation#9]
I follow ”readme“ to reproduce results， but i find the function, `tester.py->nflpipeline.py->class NFLPipeline->get_numbers()`, use gt_mask as masks to calculate metrics。 Is this reasonable？ I think whether learnable raydrop should be used as a mask for rendering  to calculate metrics（to be honest, it will lead to a decrease in indicators）. I hope to receive your reply，this is beneficial for comparing your work fairly。
Thank you again for your open-source work，it‘s Impressive。 @ShengyuH

**Comment by hanfeng-wu** [comment]
Hi, we used the GT-mask for every implemented method in our paper(LiDARsim UniSim) to produce the metrics in order to ensure point-wise alignment with the GT LiDAR scan. To produce the visual output, we use the learned raydrop mask.

**Comment by cqf7419** [comment]
> Hi, we used the GT-mask for every implemented method in our paper(LiDARsim UniSim) to produce the metrics in order to ensure point-wise alignment with the GT LiDAR scan. To produce the visual output, we use the learned raydrop mask.

Thank you for your reply。We will explain this in our experiment and compare it with the fully rendered result。
